In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('crop yield data sheet.csv')
df.head()

Rain Fall (mm)  Fertilizer Temperatue  Nitrogen (N)  Phosphorus (P)  \
0          1230.0        80.0         28          80.0            24.0   
1           480.0        60.0         36          70.0            20.0   
2          1250.0        75.0         29          78.0            22.0   
3           450.0        65.0         35          70.0            19.0   
4          1200.0        80.0         27          79.0            22.0   

   Potassium (K)  Yeild (Q/acre)  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0           20.0            12.0         NaN         NaN         NaN   
1           18.0             8.0         NaN         NaN         NaN   
2           19.0            11.0         NaN         NaN         NaN   
3           18.0             9.0         NaN         NaN         NaN   
4           19.0            11.0         NaN         NaN         NaN   

   Unnamed: 10  Unnamed: 11  Unnamed: 12  
0          NaN          NaN          NaN  
1          NaN          NaN          NaN  
2          NaN          NaN          NaN  
3          NaN          NaN          NaN  
4          NaN          NaN          NaN

In [3]:
df=df.dropna(axis=1, how='all')

In [4]:
df.isnull().value_counts()

Rain Fall (mm)  Fertilizer  Temperatue  Nitrogen (N)  Phosphorus (P)  Potassium (K)  Yeild (Q/acre)
False           False       False       False         False           False          False             99
True            True        True        True          True            True           True              26
                            False       True          True            True           True               1
dtype: int64

In [5]:
df=df.dropna(axis=0, how = 'all')
df

Rain Fall (mm)  Fertilizer Temperatue  Nitrogen (N)  Phosphorus (P)  \
0            1230.0        80.0         28          80.0            24.0   
1             480.0        60.0         36          70.0            20.0   
2            1250.0        75.0         29          78.0            22.0   
3             450.0        65.0         35          70.0            19.0   
4            1200.0        80.0         27          79.0            22.0   
..              ...         ...        ...           ...             ...   
95            425.0        60.0         39          65.0            19.0   
96           1220.0        79.0         28          77.0            23.0   
97            480.0        65.0         36          68.0            21.0   
98           1230.0        80.0         28          80.0            24.0   
108             NaN         NaN          :           NaN             NaN   

     Potassium (K)  Yeild (Q/acre)  
0             20.0            12.0  
1             18.0             8.0  
2             19.0            11.0  
3             18.0             9.0  
4             19.0            11.0  
..             ...             ...  
95            17.0             7.0  
96            21.0            11.0  
97            16.0             7.0  
98            20.0            12.0  
108            NaN             NaN  

[100 rows x 7 columns]

In [6]:
df=df.rename(columns={'Rain Fall (mm)':'rainfall','Temperatue':'temp','Nitrogen (N)':'nitrogen','Phosphorus (P)':'phos','Potassium (K)':'potassium','Yeild (Q/acre)':'production'})

In [7]:
df

rainfall  Fertilizer temp  nitrogen  phos  potassium  production
0      1230.0        80.0   28      80.0  24.0       20.0        12.0
1       480.0        60.0   36      70.0  20.0       18.0         8.0
2      1250.0        75.0   29      78.0  22.0       19.0        11.0
3       450.0        65.0   35      70.0  19.0       18.0         9.0
4      1200.0        80.0   27      79.0  22.0       19.0        11.0
..        ...         ...  ...       ...   ...        ...         ...
95      425.0        60.0   39      65.0  19.0       17.0         7.0
96     1220.0        79.0   28      77.0  23.0       21.0        11.0
97      480.0        65.0   36      68.0  21.0       16.0         7.0
98     1230.0        80.0   28      80.0  24.0       20.0        12.0
108       NaN         NaN    :       NaN   NaN        NaN         NaN

[100 rows x 7 columns]

In [8]:
df=df.iloc[:-1,:]
df

rainfall  Fertilizer temp  nitrogen  phos  potassium  production
0     1230.0        80.0   28      80.0  24.0       20.0        12.0
1      480.0        60.0   36      70.0  20.0       18.0         8.0
2     1250.0        75.0   29      78.0  22.0       19.0        11.0
3      450.0        65.0   35      70.0  19.0       18.0         9.0
4     1200.0        80.0   27      79.0  22.0       19.0        11.0
..       ...         ...  ...       ...   ...        ...         ...
94    1250.0        77.0   28      78.0  23.0       20.0         9.0
95     425.0        60.0   39      65.0  19.0       17.0         7.0
96    1220.0        79.0   28      77.0  23.0       21.0        11.0
97     480.0        65.0   36      68.0  21.0       16.0         7.0
98    1230.0        80.0   28      80.0  24.0       20.0        12.0

[99 rows x 7 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99 entries, 0 to 98
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   rainfall    99 non-null     float64
 1   Fertilizer  99 non-null     float64
 2   temp        99 non-null     object 
 3   nitrogen    99 non-null     float64
 4   phos        99 non-null     float64
 5   potassium   99 non-null     float64
 6   production  99 non-null     float64
dtypes: float64(6), object(1)
memory usage: 6.2+ KB


In [10]:
df.head()

rainfall  Fertilizer temp  nitrogen  phos  potassium  production
0    1230.0        80.0   28      80.0  24.0       20.0        12.0
1     480.0        60.0   36      70.0  20.0       18.0         8.0
2    1250.0        75.0   29      78.0  22.0       19.0        11.0
3     450.0        65.0   35      70.0  19.0       18.0         9.0
4    1200.0        80.0   27      79.0  22.0       19.0        11.0

In [11]:
x = df[['rainfall','Fertilizer','temp','nitrogen','phos','potassium']]
y = df[['production']]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
clf = DecisionTreeClassifier(criterion='entropy')

In [16]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [17]:
y_pred = clf.predict(X_test)

In [18]:
y_pred

array([10., 10., 11., 10., 10., 12.,  7.,  9., 10.,  9.,  7.,  9.,  7.,
        7., 12., 10., 10., 10.,  7.,  7.])

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
accuracy_score(y_test,y_pred)

0.45

#  Random Forest

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
clf1 = RandomForestClassifier()

In [23]:
clf1.fit(X_train, y_train)

C:\Users\Sidd-pc\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [24]:
y_pred = clf1.predict(X_test)

In [25]:
y_pred

array([10., 11., 11., 10., 10., 11.,  7.,  7., 11.,  9.,  7.,  9.,  7.,
        7., 12., 11., 10., 11.,  7.,  7.])

In [26]:
accuracy_score(y_test,y_pred)

0.5

# Support Vector Classifier

In [27]:
from sklearn.svm import SVC

In [29]:
clf3 = SVC(kernel='linear')


In [31]:
clf3.fit(X_train,y_train)

C:\Users\Sidd-pc\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [33]:
y_pred = clf3.predict(X_test)

In [34]:
y_pred

array([10., 11., 11., 10., 10., 11.,  6.,  7., 11., 11.,  6.,  9.,  7.,
        7., 12., 11., 10., 11.,  8.,  7.])

In [35]:
y_test

production
2         11.0
18        11.0
46        11.0
68        10.0
86        10.0
19        12.0
20         6.0
81         8.0
90        11.0
40        11.0
89         7.0
35         9.0
11         8.0
93         8.0
10        12.0
36        10.0
34        10.0
42        11.0
87         8.0
71         8.0

In [36]:
accuracy_score(y_test,y_pred)

0.6