In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('TitanicSurvival.csv')
df

Name survived  gender passengerClass
0       Allen, Miss. Elisabeth Walton      yes  female            1st
1      Allison, Master. Hudson Trevor      yes    male            1st
2        Allison, Miss. Helen Loraine       no  female            1st
3     Allison, Mr. Hudson Joshua Crei       no    male            1st
4     Allison, Mrs. Hudson J C (Bessi       no  female            1st
...                               ...      ...     ...            ...
1304             Zabour, Miss. Hileni       no  female            3rd
1305            Zabour, Miss. Thamine       no  female            3rd
1306        Zakarian, Mr. Mapriededer       no    male            3rd
1307              Zakarian, Mr. Ortin       no    male            3rd
1308               Zimmerman, Mr. Leo       no    male            3rd

[1309 rows x 4 columns]

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
le=LabelEncoder()

In [40]:
df['gender']=le.fit_transform(df['gender'])
df

Name  survived  gender passengerClass
0       Allen, Miss. Elisabeth Walton         1       0            1st
1      Allison, Master. Hudson Trevor         1       1            1st
2        Allison, Miss. Helen Loraine         0       0            1st
3     Allison, Mr. Hudson Joshua Crei         0       1            1st
4     Allison, Mrs. Hudson J C (Bessi         0       0            1st
...                               ...       ...     ...            ...
1304             Zabour, Miss. Hileni         0       0            3rd
1305            Zabour, Miss. Thamine         0       0            3rd
1306        Zakarian, Mr. Mapriededer         0       1            3rd
1307              Zakarian, Mr. Ortin         0       1            3rd
1308               Zimmerman, Mr. Leo         0       1            3rd

[1309 rows x 4 columns]

In [41]:
df['survived']=le.fit_transform(df['survived'])
df

Name  survived  gender passengerClass
0       Allen, Miss. Elisabeth Walton         1       0            1st
1      Allison, Master. Hudson Trevor         1       1            1st
2        Allison, Miss. Helen Loraine         0       0            1st
3     Allison, Mr. Hudson Joshua Crei         0       1            1st
4     Allison, Mrs. Hudson J C (Bessi         0       0            1st
...                               ...       ...     ...            ...
1304             Zabour, Miss. Hileni         0       0            3rd
1305            Zabour, Miss. Thamine         0       0            3rd
1306        Zakarian, Mr. Mapriededer         0       1            3rd
1307              Zakarian, Mr. Ortin         0       1            3rd
1308               Zimmerman, Mr. Leo         0       1            3rd

[1309 rows x 4 columns]

In [47]:
df['passengerClass']=le.fit_transform(df['passengerClass'])

df

Name  survived  gender  passengerClass
0       Allen, Miss. Elisabeth Walton         1       0               0
1      Allison, Master. Hudson Trevor         1       1               0
2        Allison, Miss. Helen Loraine         0       0               0
3     Allison, Mr. Hudson Joshua Crei         0       1               0
4     Allison, Mrs. Hudson J C (Bessi         0       0               0
...                               ...       ...     ...             ...
1304             Zabour, Miss. Hileni         0       0               2
1305            Zabour, Miss. Thamine         0       0               2
1306        Zakarian, Mr. Mapriededer         0       1               2
1307              Zakarian, Mr. Ortin         0       1               2
1308               Zimmerman, Mr. Leo         0       1               2

[1309 rows x 4 columns]

In [52]:
#gender and passenger class
x=df.iloc[:,[2,3]].values

In [49]:
y=df.iloc[:,1].values

In [50]:
y

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
x

array([[0, 0],
       [1, 0],
       [0, 0],
       ...,
       [1, 2],
       [1, 2],
       [1, 2]], dtype=int64)

In [53]:
from sklearn.model_selection import train_test_split


In [54]:
x_train,x_test,y_train, y_test=train_test_split(x,y,test_size=0.2)

In [55]:
from sklearn.preprocessing import StandardScaler

In [56]:
st_x=StandardScaler()

In [57]:
x_train=st_x.fit_transform(x_train)

In [58]:
x_test=st_x.transform(x_test)

In [59]:
from sklearn.linear_model import LogisticRegression

In [60]:
clf=LogisticRegression()

In [61]:
clf.fit(x_train,y_train)

LogisticRegression()

In [62]:
y_pred=clf.predict(x_test)

In [63]:
y_pred

array([0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
      dtype=int64)

In [64]:
from sklearn.metrics import confusion_matrix

In [65]:
cm=confusion_matrix(y_pred,y_test)

In [66]:
cm

array([[143,  36],
       [ 19,  64]], dtype=int64)